spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.cache.interceptor.CacheInterceptor: TRACE
